CREATE TABLE applicants (
    id INT AUTO_INCREMENT PRIMARY KEY,
    applicant_name VARCHAR(255),
    father_name VARCHAR(255),
    mother_name VARCHAR(255),
    birth_date DATE,
    mobile VARCHAR(15),
    gender VARCHAR(10),
    religion VARCHAR(50),
    blood_group VARCHAR(5),
    nationality VARCHAR(50),
    national_id VARCHAR(20),
    email VARCHAR(255),
    present_address TEXT,
    permanent_address TEXT,
    ssc_exam_type VARCHAR(50),
    ssc_board VARCHAR(100),
    ssc_roll_no VARCHAR(20),
    ssc_result VARCHAR(50),
    ssc_gpa DECIMAL(3, 2),
    ssc_group VARCHAR(50),
    ssc_pass_year YEAR,
    hsc_exam_type VARCHAR(50),
    hsc_board VARCHAR(100),
    hsc_roll_no VARCHAR(20),
    hsc_result VARCHAR(50),
    hsc_gpa DECIMAL(3, 2),
    hsc_group VARCHAR(50),
    hsc_pass_year YEAR,
    grad_exam_type VARCHAR(50),
    grad_subject VARCHAR(100),
    grad_university VARCHAR(100),
    grad_result VARCHAR(50),
    grad_cgpa DECIMAL(4, 2),
    grad_pass_year YEAR,
    ms_exam_type VARCHAR(50),
    ms_subject VARCHAR(100),
    ms_university VARCHAR(100),
    ms_result VARCHAR(50),
    ms_cgpa DECIMAL(4, 2),
    ms_pass_year YEAR,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
